### ISSUE TITLE
[feature request] Automatically translate Chinese issues or pull requests

### ISSUE THREAD

**Issue by Frankzhaopku** [pouchcontainer/pouchrobot#84]
### Ⅰ. Issue Description
We need translate Chinese (or even other language) to English automatically for globalization consideration. Need to keep the original version with English version and supposal notice.

**Comment by Frankzhaopku** [comment]
Xiaolang suggest that auto translation should directly override the issue, at least issue title to English. non English version should be like comment or even just replaced, WDYT? @allencloud

**Comment by allencloud** [comment]
This is an issue about better or best. In my opinion, our target is always set on best, while when we are trying approach best, we can first walk along with better. Just let the bullet fly for a while. Maybe we can can achieve more input. With more input, we have more confidence in doing best. @Frankzhaopku

**Comment by Frankzhaopku** [comment]
I think title translation replace is fair because this is quite important to have all English issues in the list and I will keep original version as comment first to see the feedback.
