### ISSUE TITLE
[bug] every weekly report always report 30 pull requests, it is not true

### ISSUE THREAD

**Issue by allencloud** [pouchcontainer/pouchrobot#9]
like the title of this PR, you see https://github.com/alibaba/pouch/issues/1223, and other weekly report . We always find it reports exactlt 30 pull requests.

like : 

> Thanks to contributions from community, Pouch team merged 30 pull requests in the Pouch repositories last week. All these pull requests could be divided into feature, bugfix, doc, test and others:

I think this is a bug which needs fixed.

also cc @zhuangqh

**Comment by zhuangqh** [comment]
Actually it is a bug. Robot reports exactly 30 pr, which is different from what I got from website end. I am trying to fix it. @allencloud
